apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: whatsapp-analytics-production

namespace: whatsapp-analytics-prod

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml

replicas:
- name: whatsapp-analytics-api
  count: 5

images:
- name: whatsapp-analytics-api
  newName: YOUR_ECR_REGISTRY/whatsapp-analytics-api
  newTag: latest

commonLabels:
  environment: production

