apiVersion: v1
kind: ConfigMap
metadata:
  name: whatsapp-analytics-config
  labels:
    app: whatsapp-analytics-api
data:
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  CORS_ORIGIN: "*"
  CORS_CREDENTIALS: "true"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  JWT_EXPIRES_IN: "24h"

