apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: whatsapp-analytics-base

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- secret.yaml
- ingress.yaml
- hpa.yaml
- mongodb-deployment.yaml

commonLabels:
  app: whatsapp-analytics-api
  component: backend

images:
- name: whatsapp-analytics-api
  newTag: latest

