apiVersion: v1
kind: Secret
metadata:
  name: whatsapp-analytics-secrets
  labels:
    app: whatsapp-analytics-api
type: Opaque
data:
  # Base64 encoded values - REPLACE WITH ACTUAL VALUES
  # Use: echo -n "your-value" | base64
  jwt-secret: eW91ci1qd3Qtc2VjcmV0LWhlcmU=  # your-jwt-secret-here
  whatsapp-token: eW91ci13aGF0c2FwcC10b2tlbi1oZXJl  # your-whatsapp-token-here
  whatsapp-phone-number-id: eW91ci1waG9uZS1udW1iZXItaWQtaGVyZQ==  # your-phone-number-id-here
  whatsapp-webhook-verify-token: eW91ci13ZWJob29rLXZlcmlmeS10b2tlbi1oZXJl  # your-webhook-verify-token-here
  whatsapp-webhook-secret: eW91ci13ZWJob29rLXNlY3JldC1oZXJl  # your-webhook-secret-here
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAbG9jYWxob3N0OjU0MzIvd2hhdHNhcHBfYW5hbHl0aWNz  # postgresql://user:password@localhost:5432/whatsapp_analytics

