apiVersion: v1
kind: Service
metadata:
  name: whatsapp-analytics-api-service
  labels:
    app: whatsapp-analytics-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: whatsapp-analytics-api

