apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datacompass

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

commonLabels:
  environment: staging
  app: whatsapp-analytics-api

replicas:
- name: whatsapp-analytics-api
  count: 2

