apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: datacompass-python

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mongodb-deployment.yaml
  - app-deployment.yaml
  - ingress.yaml
  - hpa.yaml
  - networkpolicy.yaml
  - rbac.yaml
  - monitoring.yaml

commonLabels:
  app: datacompass
  version: python
  environment: production

images:
  - name: datacompass-python
    newTag: latest

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: datacompass-python-app
      namespace: datacompass-python
    spec:
      template:
        spec:
          serviceAccountName: datacompass-python-sa